"""campaign include_custom

Revision ID: 0c500511ff19
Revises: 560a7b8ee1b1
Create Date: 2017-05-15 14:35:16.351331

"""

# revision identifiers, used by Alembic.
revision = '0c500511ff19'
down_revision = '560a7b8ee1b1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_custom', sa.String(length=100), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('include_custom')

    ### end Alembic commands ###
