""" scheduled_calls_job_id

Revision ID: 22e7c1f69475
Revises: 58fd841f12d7
Create Date: 2017-06-28 12:42:17.200680

"""

# revision identifiers, used by Alembic.
revision = '22e7c1f69475'
down_revision = '58fd841f12d7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('num_calls',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text(u'0'))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_call', schema=None) as batch_op:
        batch_op.alter_column('num_calls',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text(u'0'))
        batch_op.drop_column('job_id')

    ### end Alembic commands ###
