"""scheduled_calls

Revision ID: 2e693a9ad462
Revises: 7901940f204e
Create Date: 2017-06-08 20:25:09.308586

"""

# revision identifiers, used by Alembic.
revision = '2e693a9ad462'
down_revision = '7901940f204e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('time_to_call', sa.Time(), nullable=True),
    sa.Column('last_called', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_calls', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_schedule', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('prompt_schedule')

    op.drop_table('schedule_call')
    ### end Alembic commands ###
