"""add target offices

Revision ID: 39b878094b02
Revises: f3a7c22264fe
Create Date: 2017-03-16 15:38:48.261365

"""

# revision identifiers, used by Alembic.
revision = '39b878094b02'
down_revision = 'f3a7c22264fe'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_target_office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['campaign_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_offices', sa.String(length=100), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('target_offices')

    op.drop_table('campaign_target_office')
    ### end Alembic commands ###
