"""add campaign country model

Revision ID: 6c7bb8aaf6cb
Revises: 3c34cfd19bf8
Create Date: 2016-09-12 16:41:10.506362

"""

# revision identifiers, used by Alembic.
revision = '6c7bb8aaf6cb'
down_revision = '3c34cfd19bf8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_country_country_code'), ['country_code'], unique=True)

    with op.batch_alter_table(u'campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_country', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'campaign_country', ['campaign_country'], ['id'])

    with op.batch_alter_table(u'campaign_recording', schema=None) as batch_op:
        batch_op.drop_constraint(u'fk_campaign_recording_campaign_id_campaign_campaign', type_='foreignkey')
        batch_op.drop_column('selected')
        batch_op.drop_column('campaign_id')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'campaign_recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('selected', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key(u'fk_campaign_recording_campaign_id_campaign_campaign', 'campaign_campaign', ['campaign_id'], ['id'])

    with op.batch_alter_table(u'campaign_campaign', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campaign_country')

    with op.batch_alter_table('campaign_country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_country_country_code'))

    op.drop_table('campaign_country')
    ### end Alembic commands ###
