"""add campaign country code

Revision ID: 76b8da7e112d
Revises: 3c34cfd19bf8
Create Date: 2016-09-20 15:04:05.740203

"""

# revision identifiers, used by Alembic.
revision = '76b8da7e112d'
down_revision = '3c34cfd19bf8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=100), nullable=True, server_default='us'))
        batch_op.create_index(batch_op.f('ix_campaign_campaign_country_code'), ['country_code'])

    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.drop_constraint(u'fk_campaign_recording_campaign_id_campaign_campaign', type_='foreignkey')
        batch_op.drop_column('selected')
        batch_op.drop_column('campaign_id')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('selected', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key(u'fk_campaign_recording_campaign_id_campaign_campaign', 'campaign_campaign', ['campaign_id'], ['id'])

    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_campaign_country_code'))
        batch_op.drop_column('country_code')

    ### end Alembic commands ###
