"""target_district

Revision ID: 7901940f204e
Revises: 0c500511ff19
Create Date: 2017-05-30 14:26:32.304974

"""

# revision identifiers, used by Alembic.
revision = '7901940f204e'
down_revision = '0c500511ff19'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_target', schema=None) as batch_op:
        batch_op.drop_column('district')

    ### end Alembic commands ###
