"""call_session queue_delay

Revision ID: 9548e77a5e49
Revises: 22e7c1f69475
Create Date: 2017-07-10 10:21:57.307592

"""

# revision identifiers, used by Alembic.
revision = '9548e77a5e49'
down_revision = '22e7c1f69475'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_delay', sa.Interval(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls_session', schema=None) as batch_op:
        batch_op.drop_column('queue_delay')

    ### end Alembic commands ###
