"""campaign allow international calls

Revision ID: ae2d9ad59424
Revises: a47e5ebb013e
Create Date: 2017-08-30 15:21:06.406736

"""

# revision identifiers, used by Alembic.
revision = 'ae2d9ad59424'
down_revision = 'a47e5ebb013e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_intl_calls', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('allow_intl_calls')

    ### end Alembic commands ###
