"""blocklist

Revision ID: d1cbc9f7003c
Revises: 9548e77a5e49
Create Date: 2017-07-11 13:14:08.960764

"""

# revision identifiers, used by Alembic.
revision = 'd1cbc9f7003c'
down_revision = '9548e77a5e49'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires', sa.Interval(), nullable=True),
    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=16), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True, server_default='0'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_blocklist')
    ### end Alembic commands ###
